#!/bin/bash
# Bash /etc/init.d script for pyrftd

COMMAND="${1}"

function printHelp()
	{
	local PROGRAM_NAME="${1}"
	echo "usage: ${PROGRAM_NAME} {start|status|stop|reload|restart}"
	echo
	}

case "${COMMAND}" in
	"start")
		echo "Start PyRTFd"
		;;
	"status")
		echo "PyRTFd Status"
		;;
	"stop")
		echo "Stop PyRTFd"
		;;
	"reload")
		echo "PyRTFd Reload Configuration"
		;;
	"restart")
		echo "Restart PyRFTd"
		${0} stop
		if [ $? -eq 0 ]; then
			sleep 1
			${0} start
		fi
		;;
	*)
		printHelp ${0}
		;;
esac
